### ISSUE TITLE
spawn_link overhead is slow

### ISSUE THREAD

**Issue by nathany-copia** [scripbox/ex-xirr#5]
**Describe the bug**

Thanks for the library. We are currently using `LegacyFinance.xirr()` which matches our expectations for the results. It is quite a bit slower than the newer version, but the slowness is unnecessary. Removing `pmap` results in a dramatic speed up. As a test, I created a `Finance` based on `LegacyFinance` module that replaces `pmap` with `Enum.map`. This is the result using your benchmark:

```
##### With input date_values #####
Name                     ips        average  deviation         median         99th %
finance               3.93 K      254.18 μs     ±2.71%      252.99 μs      272.99 μs
ex xirr               3.25 K      307.28 μs    ±12.77%      299.99 μs      421.99 μs
legacy finance        0.44 K     2284.52 μs     ±6.76%     2273.99 μs     2761.35 μs
```

As you can see, there is an order of magnitude speedup simply by making this change.

I did some experimentation with `Stream.map` as well, but it turned out that `Enum.map` was the fastest.

**Comment by goodhamgupta** [comment]
Hello @anmlnath,

My apologies for the delayed response. Thank you for suggesting this change! 

Using `Enum.map` is indeed much faster than pmap, and I've made a quick PR to address this issue. I've also edited the benchmark files, which show numbers very similar to the ones you've posted above! Do let us know if you would like to see any additional changes in the PR. 

Thanks! 😄

**Comment by nathany-copia** [comment]
thanks @goodhamgupta

**Comment by vasuadari** [comment]
Hello @anmlnath,

Thanks for your findings. Sorry for the delay.

Hey @goodhamgupta, Thanks for the MR man :)
